window.nounsData = [
  { "english": "Vulture / bird", "glyphs": "𓄿𓏤", "transliteration": "A" },
  { "english": "Mound of ruins", "glyphs": "𓄿𓄿𓈇𓏤", "transliteration": "AA" },
  { "english": "Nubian chieftain", "glyphs": "𓄿𓄿𓏏𓄿𓂡𓀐", "transliteration": "AAtA" },
  { "english": "Viscera", "glyphs": "𓄿𓇋𓋴𓐎𓄿𓋴𓐎𓇋𓋴𓐎𓄿𓊃𓐎", "transliteration": "Ais" },
  { "english": "Translator", "glyphs": "𓄿𓂝𓂝𓍢𓋮𓀜", "transliteration": "Aaa" },
  { "english": "Container (for papyri)", "glyphs": "𓄿𓄿𓅱𓏏𓌻", "transliteration": "Aawt" },
  { "english": "Oppression", "glyphs": "𓄿𓄿𓃀𓏏𓏭", "transliteration": "Aabt" },
  { "english": "Death", "glyphs": "𓄫𓅱𓇌𓇨", "transliteration": "Aw" },
  { "english": "Long knife", "glyphs": "𓄿𓅱𓏏𓏴", "transliteration": "Awt" },
  { "english": "Gifts / oblations", "glyphs": "𓄿𓅱𓏏𓊹", "transliteration": "Awt" },
  { "english": "Length of time", "glyphs": "𓄿𓅱𓏏𓎺𓌻", "transliteration": "Awt" },
  { "english": "Panther / leopard", "glyphs": "𓄿𓃀𓏭𓊃𓊃𓐍", "transliteration": "Aby" },
  { "english": "Ivory", "glyphs": "𓄿𓃀𓅱𓌟𓄏", "transliteration": "Abw" },
  { "english": "Elephant", "glyphs": "𓍋𓃀𓅱𓃰", "transliteration": "Abw" },
  { "english": "Scorching knife / scorch", "glyphs": "𓄿𓃀𓅱𓋙", "transliteration": "Abw" },
  { "english": "Shape / form", "glyphs": "𓄿𓃀𓅱𓏏𓏤𓌻", "transliteration": "Abwt" },
  { "english": "Household / family", "glyphs": "𓄿𓃀𓏏𓌪𓀀𓁐𓏥", "transliteration": "Abt" },
  { "english": "Monthly festival", "glyphs": "𓄿𓃀𓂧𓇳", "transliteration": "Abd" },
  { "english": "Leopard-skin", "glyphs": "𓃀𓅡𓄿𓌻𓂡", "transliteration": "bA" },
  { "english": "Leopard", "glyphs": "𓃀𓅡𓄇𓄛", "transliteration": "bA" },
  { "english": "Ram", "glyphs": "𓃀𓅡𓃮𓃀𓅡𓄿𓄛", "transliteration": "bA" },
  { "english": "Spirit / soul", "glyphs": "𓅡𓅽𓏤", "transliteration": "bA" },
  { "english": "Virility", "glyphs": "𓃀𓅡𓄿𓄿𓍢𓏏𓂺", "transliteration": "bAAwt" },
  { "english": "Galley", "glyphs": "𓃀𓅡𓄿𓍢𓊛𓏤", "transliteration": "bAw" },
  { "english": "Power / deed of power", "glyphs": "𓅢𓏛𓏥𓅢𓅱𓏛𓏥", "transliteration": "bAw" },
  { "english": "Servant", "glyphs": "𓃀𓅡𓎡𓀀", "transliteration": "bAk" },
  { "english": "Cake", "glyphs": "𓃀𓅡𓎡𓃀𓅡𓎡", "transliteration": "bAkbAk" },
  { "english": "Maidservant", "glyphs": "𓅡𓎡𓏏𓁐", "transliteration": "bAkt" },
  { "english": "Dagger", "glyphs": "𓃀𓅡𓎼𓇓𓍢𓈔𓃀𓎼𓌣𓅱𓌑", "transliteration": "bAgsw" },
  { "english": "Town / city", "glyphs": "𓊖𓏏𓏤𓊖", "transliteration": "niwt" }
]
