window.phrasesData = [
  { "english": "Lay hands on", "glyphs": "𓄫𓅱𓇌𓀜𓂧𓏏𓏤", "transliteration": "Awy-Drt" },
  { "english": "Announce (someone)", "glyphs": "𓄫𓅱𓇌𓀜𓄿𓄫𓅱", "transliteration": "Awy, Awi" },
  { "english": "Present an offering", "glyphs": "𓄫𓅱𓇌𓀜𓄫𓍢𓂡", "transliteration": "Awy, Awi" },
  { "english": "Your humble servant", "glyphs": "𓅡𓎡𓀀𓇋𓅓", "transliteration": "bAk im" },
  { "english": "Souls of Heliopolis (royal ancestors)", "glyphs": "𓅢𓉺𓏌𓊖", "transliteration": "bAw iwnw" },
  { "english": "Forever / in perpetuity", "glyphs": "𓅓𓄫𓏏𓏛𓆓𓏏𓇿", "transliteration": "m Awt Dt" },
  { "english": "Today", "glyphs": "𓅓𓏇𓇋𓈖𓇳", "transliteration": "m min" },
  { "english": "Daily", "glyphs": "𓅓𓏠𓈖𓏏𓇳", "transliteration": "m mnt" },
  { "english": "Again", "glyphs": "𓅓𓄙𓅓𓂝𓏤", "transliteration": "m-wHm-a" },
  { "english": "Anew", "glyphs": "𓅓𓌳𓄿𓅱𓏏𓏛", "transliteration": "m mAwt" },
  { "english": "Also / likewise", "glyphs": "𓅓𓂋𓄿", "transliteration": "m r-a" },
  { "english": "Accordingly / likewise", "glyphs": "𓅓𓏤𓏏𓏤𓏭", "transliteration": "m mitt" },
  { "english": "By the help of", "glyphs": "𓅓𓂋𓏤𓄿𓅱𓏭", "transliteration": "m-r-awy" },
  { "english": "Together with / in the company of", "glyphs": "𓅓𓄿𓃀", "transliteration": "m-ab" },
  { "english": "In reality", "glyphs": "𓈖𓅱𓈖𓏤𓅓𓏥𓌢𓄿𓄿", "transliteration": "n wn mAa" },
  { "english": "Never", "glyphs": "𓂜𓊃𓊪𓊗", "transliteration": "n sp" },
  { "english": "In the capacity of", "glyphs": "𓈖𓊃𓃀𓈎𓂜", "transliteration": "n SAw n" },
  { "english": "Continuous / eternal / endless", "glyphs": "𓈖𓅱𓋴𓇿", "transliteration": "n-ws" },
  { "english": "City of eternity (necropolis)", "glyphs": "𓊖𓏏𓏤𓊖𓏏𓇿𓈗𓏛𓇿", "transliteration": "niwt nt nHH" },
  { "english": "Southern city (Thebes)", "glyphs": "𓊖𓏏𓏤𓊖𓂋𓊃𓏏", "transliteration": "niwt rsyt" },
  { "english": "In words / orally", "glyphs": "𓂋𓅓𓂧𓏏", "transliteration": "r-mdt" },
  { "english": "At the proper time", "glyphs": "𓂋𓈖𓍇𓏌𓅱𓇳", "transliteration": "r-nw" },
  { "english": "In the presence of", "glyphs": "𓂋𓏤𓂋𓄿", "transliteration": "r r-a" },
  { "english": "Before / in front of", "glyphs": "𓂋𓎛𓄿𓏏", "transliteration": "r-HAt" },
  { "english": "Outside", "glyphs": "𓂋𓂋𓅱𓏏𓏭", "transliteration": "r rwty" },
  { "english": "Egypt", "glyphs": "𓇾𓈖𓏏𓈖𓏏𓁷", "transliteration": "tA-mri" },
  { "english": "Lower Egypt", "glyphs": "𓇾𓏞𓐍𓈖𓅱", "transliteration": "tA-mHw" },
  { "english": "Upper Egypt", "glyphs": "𓇾𓇗𓇾𓇗𓂝𓅱𓈈", "transliteration": "tA-Smaw" },
  { "english": "God’s land", "glyphs": "𓊹𓇾𓈉", "transliteration": "tA-nTr" },
  { "english": "Sacred land (necropolis)", "glyphs": "𓇾𓂦𓇾𓈅𓏤𓂦𓂋𓈉", "transliteration": "tA-Dsr" }
]
