[
  { "english": "I", "glyphs": "𓀀", "transliteration": "" },
  { "english": "you", "glyphs": "𓎡", "transliteration": "" },
  { "english": "he", "glyphs": "𓀭", "transliteration": "" },
  { "english": "she", "glyphs": "𓁐", "transliteration": "" },
  { "english": "we", "glyphs": "𓏥", "transliteration": "" },
  { "english": "they", "glyphs": "𓏥", "transliteration": "" },
  { "english": "the", "glyphs": "𓅪", "transliteration": "" },
  { "english": "a", "glyphs": "𓄿", "transliteration": "" },
  { "english": "is", "glyphs": "𓇋𓅱", "transliteration": "" },
  { "english": "are", "glyphs": "𓃹", "transliteration": "" },
  { "english": "was", "glyphs": "𓃹", "transliteration": "" },
  { "english": "will", "glyphs": "𓆣", "transliteration": "" },
  { "english": "can", "glyphs": "𓌂", "transliteration": "" },
  { "english": "have", "glyphs": "𓎛", "transliteration": "" },
  { "english": "has", "glyphs": "𓎛", "transliteration": "" },
  { "english": "and", "glyphs": "𓎛", "transliteration": "" },
  { "english": "or", "glyphs": "𓇌", "transliteration": "" },
  { "english": "not", "glyphs": "𓂜", "transliteration": "" },
  { "english": "to", "glyphs": "𓂋", "transliteration": "" },
  { "english": "from", "glyphs": "𓅓", "transliteration": "" },
  { "english": "in", "glyphs": "𓅓", "transliteration": "" },
  { "english": "on", "glyphs": "𓁷", "transliteration": "" },
  { "english": "at", "glyphs": "𓂋", "transliteration": "" },
  { "english": "with", "glyphs": "𓎛", "transliteration": "" }
]
