[
  { "english": "sun", "glyphs": "𓇳", "transliteration": "" },
  { "english": "moon", "glyphs": "𓇴", "transliteration": "" },
  { "english": "star", "glyphs": "𓇵", "transliteration": "" },
  { "english": "water", "glyphs": "𓈖", "transliteration": "" },
  { "english": "fire", "glyphs": "𓊖", "transliteration": "" },
  { "english": "earth", "glyphs": "𓊗", "transliteration": "" },
  { "english": "air", "glyphs": "𓊘", "transliteration": "" },
  { "english": "house", "glyphs": "𓉐", "transliteration": "" },
  { "english": "temple", "glyphs": "𓉗", "transliteration": "" },
  { "english": "pyramid", "glyphs": "𓉻", "transliteration": "" },
  { "english": "boat", "glyphs": "𓊝", "transliteration": "" },
  { "english": "bird", "glyphs": "𓅿", "transliteration": "" },
  { "english": "cat", "glyphs": "𓃠", "transliteration": "" },
  { "english": "dog", "glyphs": "𓃡", "transliteration": "" },
  { "english": "snake", "glyphs": "𓆓", "transliteration": "" },
  { "english": "eye", "glyphs": "𓁹", "transliteration": "" },
  { "english": "hand", "glyphs": "𓂝", "transliteration": "" },
  { "english": "heart", "glyphs": "𓄣", "transliteration": "" },
  { "english": "bread", "glyphs": "𓏏", "transliteration": "" },
  { "english": "beer", "glyphs": "𓏲", "transliteration": "" },
  { "english": "gold", "glyphs": "𓋞", "transliteration": "" },
  { "english": "silver", "glyphs": "𓋟", "transliteration": "" },
  { "english": "life", "glyphs": "𓋹", "transliteration": "" },
  { "english": "death", "glyphs": "𓋺", "transliteration": "" },
  { "english": "king", "glyphs": "𓇓", "transliteration": "" },
  { "english": "queen", "glyphs": "𓇔", "transliteration": "" }
]
